version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'UTC'
    open-pull-requests-limit: 5
    reviewers:
      - 'Coding-Krakken'
    assignees:
      - 'Coding-Krakken'
    commit-message:
      prefix: 'deps'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automerge'
    # Group related updates
    groups:
      react-ecosystem:
        patterns:
          - 'react*'
          - '@types/react*'

      typescript-ecosystem:
        patterns:
          - 'typescript'
          - '@typescript-eslint/*'
          - '@types/*'

      testing-ecosystem:
        patterns:
          - 'vitest'
          - '@vitest/*'
          - 'playwright'
          - '@playwright/*'
          - 'jest'
          - '@testing-library/*'

      build-tools:
        patterns:
          - 'vite'
          - '@vitejs/*'
          - 'esbuild'
          - 'rollup'

      linting-formatting:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - 'prettier'

      ui-components:
        patterns:
          - '@radix-ui/*'
          - 'lucide-react'
          - 'tailwindcss'

    # Security updates
    allow:
      - dependency-type: 'all'

    # Ignore specific packages that require manual updates
    ignore:
      - dependency-name: 'node'
        update-types: ['version-update:semver-major']

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'UTC'
    open-pull-requests-limit: 3
    reviewers:
      - 'Coding-Krakken'
    assignees:
      - 'Coding-Krakken'
    commit-message:
      prefix: 'ci'
      include: 'scope'
    labels:
      - 'github-actions'
      - 'automerge'
