#!/bin/bash

echo "=== MaintAInPro Supabase Setup Helper ==="
echo ""
echo "Your Supabase project URL appears to be:"
echo "https://jthortssykpaodtbcnmq.supabase.co"
echo ""
echo "To complete the setup, you need to:"
echo ""
echo "1. Go to https://supabase.com/dashboard/project/jthortssykpaodtbcnmq"
echo "2. Navigate to Settings > API"
echo "3. Copy your 'anon public' key"
echo "4. Update your .env.local file with the key"
echo ""
echo "5. Run the database setup scripts:"
echo "   - Go to SQL Editor in Supabase dashboard"
echo "   - Run supabase/migrations/001_initial_schema.sql"
echo "   - Run supabase/migrations/002_rls_policies.sql"  
echo "   - Run database-setup.sql"
echo ""
echo "6. Create test users in Authentication > Users:"
echo "   - superadmin@acme.com (Password: SuperAdmin123!)"
echo "   - admin@acme.com (Password: OrgAdmin123!)"
echo "   - manager@acme.com (Password: Manager123!)"
echo "   - technician@acme.com (Password: Tech123!)"
echo "   - inventory@acme.com (Password: Inventory123!)"
echo "   - user@acme.com (Password: User123!)"
echo ""
echo "Your .env.local should look like:"
echo "VITE_SUPABASE_URL=https://jthortssykpaodtbcnmq.supabase.co"
echo "VITE_SUPABASE_ANON_KEY=your-anon-key-here"
