name: Automatic Domain Management

on:
  push:
    branches:
      - main # Production deployment for unitedautosupply.org
      - stable # Stable deployment for uasmaintenance.com
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update all domain aliases'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: read
  deployments: read

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  update-domain-aliases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Get Latest Deployment URL
        id: get-deployment
        run: |
          # Get the latest deployment for the current branch
          LATEST_DEPLOYMENT=$(vercel ls --scope coding-krakken-projects --token=${{ secrets.VERCEL_TOKEN }} | grep "● Ready" | grep "Production" | head -1 | awk '{print $2}' | sed 's/https:\/\///')

          if [ -z "$LATEST_DEPLOYMENT" ]; then
            echo "❌ No production deployment found"
            exit 1
          fi

          echo "Latest deployment: $LATEST_DEPLOYMENT"
          echo "deployment-url=$LATEST_DEPLOYMENT" >> $GITHUB_OUTPUT

      - name: Update Domain Aliases for Main Branch
        if: github.ref == 'refs/heads/main'
        run: |
          echo "🔄 Updating domain aliases for main branch..."
          DEPLOYMENT_URL="${{ steps.get-deployment.outputs.deployment-url }}"

          # Update unitedautosupply.org (main production domain)
          echo "Updating unitedautosupply.org..."
          vercel alias set "$DEPLOYMENT_URL" unitedautosupply.org --scope coding-krakken-projects --token=${{ secrets.VERCEL_TOKEN }}

          # Update www.unitedautosupply.org
          echo "Updating www.unitedautosupply.org..."
          vercel alias set "$DEPLOYMENT_URL" www.unitedautosupply.org --scope coding-krakken-projects --token=${{ secrets.VERCEL_TOKEN }}

          echo "✅ Main branch domains updated successfully"

      - name: Update Domain Aliases for Stable Branch
        if: github.ref == 'refs/heads/stable'
        run: |
          echo "🔄 Updating domain aliases for stable branch..."
          DEPLOYMENT_URL="${{ steps.get-deployment.outputs.deployment-url }}"

          # Update uasmaintenance.com (stable branch domain)
          echo "Updating uasmaintenance.com..."
          vercel alias set "$DEPLOYMENT_URL" uasmaintenance.com --scope coding-krakken-projects --token=${{ secrets.VERCEL_TOKEN }}

          # Update www.uasmaintenance.com
          echo "Updating www.uasmaintenance.com..."
          vercel alias set "$DEPLOYMENT_URL" www.uasmaintenance.com --scope coding-krakken-projects --token=${{ secrets.VERCEL_TOKEN }}

          echo "✅ Stable branch domains updated successfully"

      - name: Force Update All Domains (Manual Trigger)
        if: github.event.inputs.force_update == 'true'
        run: |
          echo "🔄 Force updating all domain aliases..."
          DEPLOYMENT_URL="${{ steps.get-deployment.outputs.deployment-url }}"

          # Update all domains to point to current deployment
          echo "Force updating all domains..."
          vercel alias set "$DEPLOYMENT_URL" unitedautosupply.org --scope coding-krakken-projects --token=${{ secrets.VERCEL_TOKEN }}
          vercel alias set "$DEPLOYMENT_URL" www.unitedautosupply.org --scope coding-krakken-projects --token=${{ secrets.VERCEL_TOKEN }}
          vercel alias set "$DEPLOYMENT_URL" uasmaintenance.com --scope coding-krakken-projects --token=${{ secrets.VERCEL_TOKEN }}
          vercel alias set "$DEPLOYMENT_URL" www.uasmaintenance.com --scope coding-krakken-projects --token=${{ secrets.VERCEL_TOKEN }}

          echo "✅ All domains force updated successfully"

      - name: Verify Domain Assignments
        run: |
          echo "🔍 Verifying domain assignments..."
          echo "Current aliases:"
          vercel alias ls --scope coding-krakken-projects --token=${{ secrets.VERCEL_TOKEN }} | grep -E "(unitedautosupply|uasmaintenance)"

          echo "✅ Domain verification complete"

      - name: Create Domain Update Summary
        run: |
          cat > domain-update-summary.json << EOF
          {
            "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "branch": "${{ github.ref_name }}",
            "sha": "${{ github.sha }}",
            "deploymentUrl": "${{ steps.get-deployment.outputs.deployment-url }}",
            "updatedDomains": {
              "main": $(if [ "${{ github.ref }}" = "refs/heads/main" ]; then echo '["unitedautosupply.org", "www.unitedautosupply.org"]'; else echo '[]'; fi),
              "stable": $(if [ "${{ github.ref }}" = "refs/heads/stable" ]; then echo '["uasmaintenance.com", "www.uasmaintenance.com"]'; else echo '[]'; fi),
              "force": $(if [ "${{ github.event.inputs.force_update }}" = "true" ]; then echo '["unitedautosupply.org", "www.unitedautosupply.org", "uasmaintenance.com", "www.uasmaintenance.com"]'; else echo '[]'; fi)
            },
            "actor": "${{ github.actor }}",
            "workflowRun": "${{ github.run_id }}"
          }
          EOF

          echo "Domain update summary:"
          cat domain-update-summary.json

      - name: Upload Domain Update Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: domain-update-summary-${{ github.ref_name }}-${{ github.run_number }}
          path: domain-update-summary.json
          retention-days: 30
