export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          logo: string | null;
          settings: Json;
          subscription: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          logo?: string | null;
          settings?: Json;
          subscription?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          logo?: string | null;
          settings?: Json;
          subscription?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      warehouses: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          code: string;
          address: Json;
          is_active: boolean;
          manager_id: string | null;
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          code: string;
          address: Json;
          is_active?: boolean;
          manager_id?: string | null;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          code?: string;
          address?: Json;
          is_active?: boolean;
          manager_id?: string | null;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          organization_id: string;
          email: string;
          first_name: string | null;
          last_name: string | null;
          role: string;
          permissions: Json;
          avatar_url: string | null;
          phone: string | null;
          department: string | null;
          employee_id: string | null;
          is_active: boolean;
          last_login: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          organization_id: string;
          email: string;
          first_name?: string | null;
          last_name?: string | null;
          role?: string;
          avatar_url?: string | null;
          phone?: string | null;
          department?: string | null;
          employee_id?: string | null;
          is_active?: boolean;
          last_login?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          email?: string;
          first_name?: string | null;
          last_name?: string | null;
          role?: string;
          permissions?: Json;
          avatar_url?: string | null;
          phone?: string | null;
          department?: string | null;
          employee_id?: string | null;
          is_active?: boolean;
          last_login?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      equipment: {
        Row: {
          id: string;
          organization_id: string;
          warehouse_id: string;
          name: string;
          description: string | null;
          model: string | null;
          manufacturer: string | null;
          serial_number: string | null;
          asset_tag: string | null;
          qr_code: string | null;
          location: string | null;
          category_id: string | null;
          status: string;
          condition: string;
          purchase_date: string | null;
          purchase_cost: number | null;
          warranty_expiry: string | null;
          specifications: Json | null;
          maintenance_notes: string | null;
          images: string[];
          documents: Json[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          warehouse_id: string;
          name: string;
          description?: string | null;
          model?: string | null;
          manufacturer?: string | null;
          serial_number?: string | null;
          asset_tag?: string | null;
          qr_code?: string | null;
          location?: string | null;
          category_id?: string | null;
          status?: string;
          condition?: string;
          purchase_date?: string | null;
          purchase_cost?: number | null;
          warranty_expiry?: string | null;
          specifications?: Json | null;
          maintenance_notes?: string | null;
          images?: string[];
          documents?: Json[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          warehouse_id?: string;
          name?: string;
          description?: string | null;
          model?: string | null;
          manufacturer?: string | null;
          serial_number?: string | null;
          asset_tag?: string | null;
          qr_code?: string | null;
          location?: string | null;
          category_id?: string | null;
          status?: string;
          condition?: string;
          purchase_date?: string | null;
          purchase_cost?: number | null;
          warranty_expiry?: string | null;
          specifications?: Json | null;
          maintenance_notes?: string | null;
          images?: string[];
          documents?: Json[];
          created_at?: string;
          updated_at?: string;
        };
      };
      work_orders: {
        Row: {
          id: string;
          organization_id: string;
          warehouse_id: string;
          work_order_number: string;
          title: string;
          description: string;
          type: string;
          priority: string;
          status: string;
          equipment_id: string | null;
          location: string | null;
          assigned_to: string | null;
          requested_by: string;
          estimated_hours: number | null;
          actual_hours: number | null;
          estimated_cost: number | null;
          actual_cost: number | null;
          due_date: string | null;
          started_at: string | null;
          completed_at: string | null;
          notes: string | null;
          images: string[];
          documents: Json[];
          parts_used: Json[];
          checklist: Json[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          warehouse_id: string;
          work_order_number: string;
          title: string;
          description: string;
          type: string;
          priority?: string;
          status?: string;
          equipment_id?: string | null;
          location?: string | null;
          assigned_to?: string | null;
          requested_by: string;
          estimated_hours?: number | null;
          actual_hours?: number | null;
          estimated_cost?: number | null;
          actual_cost?: number | null;
          due_date?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          notes?: string | null;
          images?: string[];
          documents?: Json[];
          parts_used?: Json[];
          checklist?: Json[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          warehouse_id?: string;
          work_order_number?: string;
          title?: string;
          description?: string;
          type?: string;
          priority?: string;
          status?: string;
          equipment_id?: string | null;
          location?: string | null;
          assigned_to?: string | null;
          requested_by?: string;
          estimated_hours?: number | null;
          actual_hours?: number | null;
          estimated_cost?: number | null;
          actual_cost?: number | null;
          due_date?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          notes?: string | null;
          images?: string[];
          documents?: Json[];
          parts_used?: Json[];
          checklist?: Json[];
          created_at?: string;
          updated_at?: string;
        };
      };
      parts: {
        Row: {
          id: string;
          organization_id: string;
          warehouse_id: string;
          name: string;
          description: string | null;
          part_number: string;
          manufacturer: string | null;
          category_id: string | null;
          unit_cost: number;
          currency: string;
          stock_quantity: number;
          reserved_quantity: number;
          min_stock_level: number;
          max_stock_level: number;
          reorder_point: number;
          unit_of_measure: string;
          location: string | null;
          supplier_id: string | null;
          supplier_part_number: string | null;
          lead_time_days: number | null;
          is_consumable: boolean;
          is_active: boolean;
          images: string[];
          specifications: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          warehouse_id: string;
          name: string;
          description?: string | null;
          part_number: string;
          manufacturer?: string | null;
          category_id?: string | null;
          unit_cost: number;
          currency?: string;
          stock_quantity?: number;
          reserved_quantity?: number;
          min_stock_level?: number;
          max_stock_level?: number;
          reorder_point?: number;
          unit_of_measure?: string;
          location?: string | null;
          supplier_id?: string | null;
          supplier_part_number?: string | null;
          lead_time_days?: number | null;
          is_consumable?: boolean;
          is_active?: boolean;
          images?: string[];
          specifications?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          warehouse_id?: string;
          name?: string;
          description?: string | null;
          part_number?: string;
          manufacturer?: string | null;
          category_id?: string | null;
          unit_cost?: number;
          currency?: string;
          stock_quantity?: number;
          reserved_quantity?: number;
          min_stock_level?: number;
          max_stock_level?: number;
          reorder_point?: number;
          unit_of_measure?: string;
          location?: string | null;
          supplier_id?: string | null;
          supplier_part_number?: string | null;
          lead_time_days?: number | null;
          is_consumable?: boolean;
          is_active?: boolean;
          images?: string[];
          specifications?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      preventive_maintenance: {
        Row: {
          id: string;
          organization_id: string;
          warehouse_id: string;
          name: string;
          description: string | null;
          equipment_id: string;
          frequency_type: string;
          frequency_value: number;
          estimated_duration: number | null;
          instructions: string | null;
          checklist: Json[];
          required_parts: Json[];
          assigned_to: string | null;
          is_active: boolean;
          next_due_date: string | null;
          last_completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          warehouse_id: string;
          name: string;
          description?: string | null;
          equipment_id: string;
          frequency_type: string;
          frequency_value: number;
          estimated_duration?: number | null;
          instructions?: string | null;
          checklist?: Json[];
          required_parts?: Json[];
          assigned_to?: string | null;
          is_active?: boolean;
          next_due_date?: string | null;
          last_completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          warehouse_id?: string;
          name?: string;
          description?: string | null;
          equipment_id?: string;
          frequency_type?: string;
          frequency_value?: number;
          estimated_duration?: number | null;
          instructions?: string | null;
          checklist?: Json[];
          required_parts?: Json[];
          assigned_to?: string | null;
          is_active?: boolean;
          next_due_date?: string | null;
          last_completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      vendors: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          type: string;
          contact_person: string | null;
          email: string | null;
          phone: string | null;
          address: Json | null;
          website: string | null;
          tax_id: string | null;
          payment_terms: string | null;
          is_active: boolean;
          rating: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          type: string;
          contact_person?: string | null;
          email?: string | null;
          phone?: string | null;
          address?: Json | null;
          website?: string | null;
          tax_id?: string | null;
          payment_terms?: string | null;
          is_active?: boolean;
          rating?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          type?: string;
          contact_person?: string | null;
          email?: string | null;
          phone?: string | null;
          address?: Json | null;
          website?: string | null;
          tax_id?: string | null;
          payment_terms?: string | null;
          is_active?: boolean;
          rating?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          type: string;
          description: string | null;
          parent_id: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          type: string;
          description?: string | null;
          parent_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          type?: string;
          description?: string | null;
          parent_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          entity_type: string;
          entity_id: string;
          action: string;
          changes: Json | null;
          user_id: string;
          user_email: string;
          ip_address: string | null;
          user_agent: string | null;
          timestamp: string;
        };
        Insert: {
          id?: string;
          entity_type: string;
          entity_id: string;
          action: string;
          changes?: Json | null;
          user_id: string;
          user_email: string;
          ip_address?: string | null;
          user_agent?: string | null;
          timestamp?: string;
        };
        Update: {
          id?: string;
          entity_type?: string;
          entity_id?: string;
          action?: string;
          changes?: Json | null;
          user_id?: string;
          user_email?: string;
          ip_address?: string | null;
          user_agent?: string | null;
          timestamp?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          message: string;
          data: Json | null;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          message: string;
          data?: Json | null;
          is_read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          title?: string;
          message?: string;
          data?: Json | null;
          is_read?: boolean;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];
