# MaintAInPro Simple Test Workflow
# Purpose: Manual and push-triggered test for basic CI validation.
# Triggers: Only runs for code changes, not docs-only edits.
name: Test Workflow
on:
  workflow_dispatch:
    paths:
      - '**/*.ts'
      - '**/*.js'
      - 'client/**'
      - 'server/**'
      - 'shared/**'
      - 'api/**'
    paths-ignore:
      - 'Documentation/**'
      - '**/*.md'
      - 'CHANGELOG.md'
  push:
    branches:
      - Replit
    paths:
      - '**/*.ts'
      - '**/*.js'
      - 'client/**'
      - 'server/**'
      - 'shared/**'
      - 'api/**'
    paths-ignore:
      - 'Documentation/**'
      - '**/*.md'
      - 'CHANGELOG.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simple test
        run: |
          echo "✅ Test workflow is working!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
