name: Test Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - Replit

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simple test
        run: |
          echo "✅ Test workflow is working!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
